language: python

python:
  - "2.7"

notifications:
  email: false

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no

  # install from conda defaults, then from public binstar if not available
  - conda config --add channels 'defaults'
  - conda config --add channels 'https://conda.binstar.org/public'

  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a

  # build package from conda recipe
  - conda install conda-build jinja2 setuptools
  - export CONDA_PY="${TRAVIS_PYTHON_VERSION//./}"
  - export CONDA_NPY=17
  - conda build --no-test conda.recipe/

  # install into test environment
  - conda create -n test-environment --use-local radarmodel python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

script: make test
